const FILTER_KEY="world-cup-brief-match-filter";
const DATA_URL="https://site.api.espn.com/apis/site/v2/sports/soccer/fifa.world/scoreboard?dates=20260611-20260719&limit=500",STORAGE_KEY="world-cup-brief-favorite-teams-v2";
const teamData="Algeria|Argelia|🇩🇿;Argentina|Argentina|🇦🇷;Australia|Australia|🇦🇺;Austria|Austria|🇦🇹;Belgium|Bélgica|🇧🇪;Bosnia-Herzegovina|Bosnia y Herzegovina|🇧🇦;Brazil|Brasil|🇧🇷;Canada|Canadá|🇨🇦;Cape Verde|Cabo Verde|🇨🇻;Colombia|Colombia|🇨🇴;Congo DR|R. D. del Congo|🇨🇩;Croatia|Croacia|🇭🇷;Curaçao|Curazao|🇨🇼;Czechia|Chequia|🇨🇿;Ecuador|Ecuador|🇪🇨;Egypt|Egipto|🇪🇬;England|Inglaterra|🏴;France|Francia|🇫🇷;Germany|Alemania|🇩🇪;Ghana|Ghana|🇬🇭;Haiti|Haití|🇭🇹;Iran|Irán|🇮🇷;Iraq|Irak|🇮🇶;Ivory Coast|Costa de Marfil|🇨🇮;Japan|Japón|🇯🇵;Jordan|Jordania|🇯🇴;Mexico|México|🇲🇽;Morocco|Marruecos|🇲🇦;Netherlands|Países Bajos|🇳🇱;New Zealand|Nueva Zelanda|🇳🇿;Norway|Noruega|🇳🇴;Panama|Panamá|🇵🇦;Paraguay|Paraguay|🇵🇾;Portugal|Portugal|🇵🇹;Qatar|Catar|🇶🇦;Saudi Arabia|Arabia Saudí|🇸🇦;Scotland|Escocia|🏴;Senegal|Senegal|🇸🇳;South Africa|Sudáfrica|🇿🇦;South Korea|Corea del Sur|🇰🇷;Spain|España|🇪🇸;Sweden|Suecia|🇸🇪;Switzerland|Suiza|🇨🇭;Tunisia|Túnez|🇹🇳;Türkiye|Turquía|🇹🇷;United States|Estados Unidos|🇺🇸;Uruguay|Uruguay|🇺🇾;Uzbekistan|Uzbekistán|🇺🇿";
const info=Object.fromEntries(teamData.split(";").map(x=>{const[a,b,c]=x.split("|");return[a,{label:b,flag:c}]})),fallback=Object.keys(info),legacy={"España 🇪🇸":"Spain","Brasil 🇧🇷":"Brazil","Argentina 🇦🇷":"Argentina","Francia 🇫🇷":"France"};
const $=s=>document.querySelector(s),picker=$("#team-picker"),status=$("#app-status"),briefs=$("#favorites-list"),planning=$("#planning-list"),standings=$("#standings-list"),count=$("#favorites-count"),refresh=$("#refresh-button"),note=$("#planning-note"),standingsTitle=$("#standings-title"),standingsEyebrow=$("#standings-eyebrow");let events=[],teams=fallback.map(name=>({name,group:""}));
const label=n=>`${info[n]?.label||n} ${info[n]?.flag||"🏳️"}`,esc=v=>String(v||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[c]);
function saved(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY));if(Array.isArray(s))return s;const old=JSON.parse(localStorage.getItem("world-cup-brief-favorite-teams"));return Array.isArray(old)?old.map(x=>legacy[x]||x):[]}catch{return[]}}
function group(c){const s=[c.altGameNote,c.headline,c.group,c.notes?.map(n=>n.headline||n.text).join(" ")].filter(Boolean).join(" "),m=s.match(/Group\s+([A-L])/i);return m?`Grupo ${m[1].toUpperCase()}`:""}
function round(c,e){const s=[c.altGameNote,c.headline,c.stage?.description,c.type?.text,e.name,e.shortName,c.notes?.map(n=>n.headline||n.text).join(" ")].filter(Boolean).join(" ");if(/round of 32|dieciseisavos|32/i.test(s))return"Dieciseisavos";if(/round of 16|octavos|16/i.test(s))return"Octavos";if(/quarter|cuartos/i.test(s))return"Cuartos";if(/semi|semifinal/i.test(s))return"Semifinales";if(/\bfinal\b/i.test(s)&&!/third|3rd|tercer/i.test(s))return"Final";return group(c)?"Grupos":""}
function icon(name){const paths={calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 10h18"/>',map:'<path d="M12 21s7-6.2 7-12a7 7 0 1 0-14 0c0 5.8 7 12 7 12z"/><circle cx="12" cy="9" r="2"/>'};return '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+paths[name]+'</svg>'}
function normal(e){const c=e.competitions?.[0],competitors=c?.competitors||[],h=competitors.find(entry=>entry.homeAway==="home"),a=competitors.find(entry=>entry.homeAway==="away");if(!c||!h||!a)return null;const statusType=c.status?.type||{};return{date:new Date(c.date||e.date),group:group(c),round:round(c,e),home:h.team.displayName,away:a.team.displayName,hs:Number(h.score)||0,as:Number(a.score)||0,done:!!statusType.completed,state:statusType.state||"",clock:c.status?.displayClock||statusType.detail||statusType.shortDetail||"",venue:c.venue?.fullName||"",city:c.venue?.address?.city||"",goals:(c.details||[]).filter(detail=>detail.scoringPlay).map(detail=>({name:detail.athletesInvolved?.[0]?.displayName,minute:detail.clock?.displayValue,own:detail.ownGoal,team:competitors.find(entry=>String(entry.id)===String(detail.team?.id))?.team.displayName}))}}
function date(d,short=false){return new Intl.DateTimeFormat("es-ES",{weekday:"short",day:"numeric",month:"short",...(short?{}:{hour:"2-digit",minute:"2-digit"}),timeZone:"Europe/Madrid"}).format(d).replaceAll(".","")}
function dayKey(d){return new Intl.DateTimeFormat("en-CA",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Europe/Madrid"}).format(d)}
function map(e){const q=encodeURIComponent([e.venue,e.city].filter(Boolean).join(" "));return navigator.userAgent.includes("iPhone")||navigator.userAgent.includes("iPad")?`maps://?q=${q}`:`https://www.google.com/maps/search/?api=1&query=${q}`}
function formatICSDate(date){return date.toISOString().replace(/[-:]/g,"").replace(/\.\d{3}Z$/,"Z")}
function escapeICS(text){return String(text||"").replace(/\\/g,"\\\\").replace(/;/g,"\\;").replace(/,/g,"\\,").replace(/\r?\n/g,"\\n")}
function buildICS(e){const a=new Date(e.date),I=new Date(a.getTime()+72e5),D=(info[e.home]?.label||e.home)+" vs "+(info[e.away]?.label||e.away),E=[e.venue,e.city].filter(Boolean).join(", "),t=formatICSDate(new Date);return["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//World Cup Brief//ES","CALSCALE:GREGORIAN","METHOD:PUBLISH","BEGIN:VEVENT","UID:"+String(e.home+"-"+e.away+"-"+a.getTime()).replace(/[^a-zA-Z0-9-]/g,"")+"@world-cup-brief","DTSTAMP:"+t,"DTSTART:"+formatICSDate(a),"DTEND:"+formatICSDate(I),"SUMMARY:"+escapeICS(D),"LOCATION:"+escapeICS(E),"DESCRIPTION:"+escapeICS("Partido del Mundial 2026"),"BEGIN:VALARM","TRIGGER:-PT15M","ACTION:DISPLAY","DESCRIPTION:"+escapeICS("El partido empieza en 15 minutos"),"END:VALARM","END:VEVENT","END:VCALENDAR"].join("\r\n")+"\r\n"}
function cal(e){if(/iPad|iPhone|iPod/.test(navigator.userAgent)||navigator.standalone){return URL.createObjectURL(new Blob([buildICS(e)],{type:"text/calendar;charset=utf-8"}))}const start=formatICSDate(e.date),end=formatICSDate(new Date(+e.date+7200000)),title=(info[e.home]?.label||e.home)+" vs "+(info[e.away]?.label||e.away),location=[e.venue,e.city].filter(Boolean).join(", ");return"https://calendar.google.com/calendar/render?action=TEMPLATE&text="+encodeURIComponent(title)+"&dates="+start+"/"+end+"&location="+encodeURIComponent(location)}
function table(g){const r=new Map(teams.filter(t=>t.group===g).map(t=>[t.name,{name:t.name,pj:0,pts:0,gf:0,gc:0}]));events.filter(e=>e.group===g&&e.done).forEach(e=>{const h=r.get(e.home),a=r.get(e.away);if(!h||!a)return;h.pj++;a.pj++;h.gf+=e.hs;h.gc+=e.as;a.gf+=e.as;a.gc+=e.hs;if(e.hs>e.as)h.pts+=3;else if(e.hs<e.as)a.pts+=3;else{h.pts++;a.pts++}});return[...r.values()].sort((a,b)=>b.pts-a.pts||(b.gf-b.gc)-(a.gf-a.gc)||b.gf-a.gf||a.name.localeCompare(b.name))}
function favs(){return saved().filter(n=>teams.some(t=>t.name===n))}
function isLive(e){return e.state==="in"&&!e.done}
function liveMinute(e){const m=String(e.clock||"").match(/\d+/);return m?`Min ${m[0]}`:"En juego"}
function phaseText(n,g,roundName){if(roundName&&roundName!=="Grupos")return roundName;if(!g)return"";const tb=table(g),pos=tb.findIndex(r=>r.name===n);return pos>=0?`${g} · ${pos+1}.º · ${tb[pos].pts} pts`:g}
function renderBriefs(sel){count.textContent=`${sel.length} equipo${sel.length===1?"":"s"}`;if(!sel.length){briefs.innerHTML='<p class="empty">Elige equipos en “Editar equipos” para ver su próximo partido, último resultado y situación de grupo.</p>';return}const now=new Date;briefs.innerHTML=sel.map(n=>{const ms=events.filter(e=>e.home===n||e.away===n),live=ms.find(isLive),last=ms.filter(e=>e.done).sort((a,b)=>b.date-a.date)[0],next=ms.filter(e=>!e.done&&!isLive(e)&&e.date>=new Date(+now-10800000)).sort((a,b)=>a.date-b.date)[0],g=teams.find(t=>t.name===n)?.group||"",roundName=(live||next||last)?.round||"",opp=next&&(next.home===n?next.away:next.home),phase=phaseText(n,g,roundName);return`<article class="brief-card ${live?"is-live":""}"><div class="brief-top"><div class="team-name"><span class="flag">${info[n]?.flag||"🏳️"}</span><div><h3>${esc(info[n]?.label||n)}</h3>${phase?`<p class="muted" style="margin:3px 0 0;font-size:.8rem">${esc(phase)}</p>`:""}</div></div></div>${live?`<section class="quick-block live-panel"><p class="live-badge">LIVE</p><p class="live-score">${esc(info[live.home]?.label||live.home)} ${live.hs}–${live.as} ${esc(info[live.away]?.label||live.away)}</p><p class="live-minute">${esc(liveMinute(live))}</p></section>`:`<section class="quick-block"><p class="quick-label">PRÓXIMO PARTIDO</p>${next?`<p class="game-title">${esc(label(n))} vs ${esc(label(opp))}</p><p class="game-meta"><a class="inline-link" href="${cal(next)}" download="world-cup-brief.ics" target="_blank" rel="noreferrer">📅 ${esc(date(next.date))}</a><br><a class="inline-link" href="${map(next)}" target="_blank" rel="noreferrer">🗺 ${esc(next.venue||"Estadio pendiente")} · ${esc(next.city||"Ciudad pendiente")}</a></p>`:'<p class="game-meta">Próximo partido pendiente de publicación.</p>'}</section>`}<section class="quick-block"><p class="quick-label">ÚLTIMO RESULTADO</p><p class="result-line">${last?`${esc(date(last.date,true))} · ${esc(label(last.home))} ${last.hs}–${last.as} ${esc(label(last.away))}`:"Aún no hay un resultado final."}</p></section></article>`}).join("")}
function renderPlanning(sel){const now=new Date,limit=new Date(+now+7*86400000),up=events.filter(e=>!e.done&&e.date>=new Date(+now-10800000)&&e.date<=limit&&(!$("#match-filter")||$("#match-filter").value==="all"||sel.includes(e.home)||sel.includes(e.away))).sort((a,b)=>a.date-b.date).slice(0,12);const mine=up.filter(e=>sel.includes(e.home)||sel.includes(e.away)).slice(0,6),other=up.filter(e=>!sel.includes(e.home)&&!sel.includes(e.away)).slice(0,8),draw=(list,title)=>list.length?`<section class="match-group"><p class="eyebrow">${title}</p>${list.map(e=>`<article class="match ${sel.includes(e.home)||sel.includes(e.away)?"favorite":""}"><p class="match-date"><a class="inline-link" href="${cal(e)}" download="world-cup-brief.ics" target="_blank" rel="noreferrer" aria-label="Añadir al calendario">${esc(date(e.date))}${isLive(e)?" · En juego":""} ${icon("calendar")}</a></p><p class="match-title">${esc(label(e.home))} vs ${esc(label(e.away))}</p><p class="match-meta">${esc(e.group||e.round||"Fase final")} · ${esc(e.venue||"Estadio pendiente")} · <a class="inline-link" href="${map(e)}" target="_blank" rel="noreferrer" aria-label="Ver mapa">${icon("map")}</a></p></article>`).join("")}</section>`:"";planning.innerHTML=(draw(mine,"MIS EQUIPOS")+draw(other,"OTROS PARTIDOS"))||'<p class="empty">No hay próximos partidos durante los próximos 7 días.</p>';note.textContent="Mostrando próximos 7 días."}
function renderGroupStandings(sel){if(standingsEyebrow)standingsEyebrow.textContent="CLASIFICACIÓN";if(standingsTitle)standingsTitle.textContent="Tus grupos";const gs=[...new Set(sel.map(n=>teams.find(t=>t.name===n)?.group).filter(Boolean))].sort();standings.innerHTML=gs.length?gs.map(g=>`<section><p class="eyebrow" style="margin-bottom:8px">${esc(g)}</p><div class="table-wrap"><table><thead><tr><th>#</th><th>Selección</th><th>PJ</th><th>PTS</th><th>GF</th><th>GC</th></tr></thead><tbody>${table(g).map((r,i)=>`<tr class="${sel.includes(r.name)?"favorite-row":""}"><td>${i+1}</td><td>${esc(label(r.name))}</td><td>${r.pj}</td><td>${r.pts}</td><td>${r.gf}</td><td>${r.gc}</td></tr>`).join("")}</tbody></table></div></section>`).join(""):'<p class="empty">Selecciona un equipo para ver la clasificación de su grupo.</p>'}
function winner(e,team){return e.done&&((team===e.home&&e.hs>e.as)||(team===e.away&&e.as>e.hs))}
function teamRow(e,team,score,sel){return`<div class="bracket-team ${winner(e,team)?"winner":""} ${sel.includes(team)?"favorite-team":""}"><span>${esc(label(team))}</span><strong>${e.done||isLive(e)?score:""}</strong></div>`}
function renderBracket(sel){if(standingsEyebrow)standingsEyebrow.textContent="CAMINO HACIA LA FINAL";if(standingsTitle)standingsTitle.textContent="Camino hacia la final";const rounds=["Dieciseisavos","Octavos","Cuartos","Semifinales","Final"];standings.innerHTML=`<div class="knockout-bracket" aria-label="Cuadro eliminatorio del Mundial">${rounds.map(r=>{const games=events.filter(e=>e.round===r).sort((a,b)=>a.date-b.date);return`<section class="bracket-round"><h3>${r}</h3>${games.length?games.map(e=>`<article class="bracket-match ${isLive(e)?"is-live":""} ${sel.includes(e.home)||sel.includes(e.away)?"has-favorite":""}"><p class="match-date">${esc(date(e.date))}${isLive(e)?' · LIVE':''}</p>${teamRow(e,e.home,e.hs,sel)}${teamRow(e,e.away,e.as,sel)}<p class="match-meta">${esc(e.venue||"Estadio pendiente")}${e.city?` · ${esc(e.city)}`:""}</p></article>`).join(""):'<p class="empty">Pendiente de definir.</p>'}</section>`}).join("")}</div>`}
function renderStandings(sel){events.some(e=>e.round&&e.round!=="Grupos")?renderBracket(sel):renderGroupStandings(sel)}
function renderPicker(){const s=new Set(saved());picker.innerHTML=teams.map(t=>`<label class="team-chip"><input type="checkbox" value="${esc(t.name)}" ${s.has(t.name)?"checked":""}>${esc(label(t.name))}</label>`).join("");picker.querySelectorAll("input").forEach(x=>x.addEventListener("change",save))}
function groupedGoalLines(goals){const grouped=new Map;goals.filter(g=>g.name).forEach(g=>{const key=`${g.name}|${g.own?"own":"goal"}`;if(!grouped.has(key))grouped.set(key,{name:g.name,own:g.own,minutes:[]});if(g.minute)grouped.get(key).minutes.push(g.minute)});return[...grouped.values()].map(g=>`<li>${esc(g.name)} ${esc(g.minutes.join(", "))}${g.own?" (PP)":""}</li>`).join("")}
function goalBlock(teamName,goals){const lines=groupedGoalLines(goals);return lines?`<div class="goal-team"><h4>${esc(info[teamName]?.label||teamName)}</h4><ul>${lines}</ul></div>`:""}
function renderRecentResults(){const now=new Date,today=dayKey(now),yesterdayDate=new Date(+now-86400000),yesterday=dayKey(yesterdayDate),games=events.filter(e=>e.done&&(dayKey(e.date)===today||dayKey(e.date)===yesterday)).sort((a,b)=>b.date-a.date),box=$("#yesterday-list"),labelEl=$("#yesterday-label");if(labelEl)labelEl.textContent="ÚLTIMOS RESULTADOS";let expanded=false;function card(e){const homeGoals=e.goals.filter(g=>g.name&&g.team===e.home),awayGoals=e.goals.filter(g=>g.name&&g.team===e.away),goalsHtml=goalBlock(e.home,homeGoals)+goalBlock(e.away,awayGoals);return `<article class="result-card"><div class="score-board"><div class="score-row"><span>${esc(label(e.home))}</span><strong>${e.hs}</strong></div><div class="score-row"><span>${esc(label(e.away))}</span><strong>${e.as}</strong></div></div><p class="match-meta result-stage">${esc(e.group||e.round||"")}</p>${goalsHtml?`<div class="goal-block"><p>Goleadores:</p>${goalsHtml}</div>`:""}</article>`}function paint(){const visible=expanded?games:games.slice(0,6);box.innerHTML=games.length?visible.map(card).join("")+(games.length>6?'<button class="more-results" id="more-yesterday">'+(expanded?"Ver menos":"Ver todos")+'</button>':''):'<p class="empty">Todavía no ha terminado ningún partido recientemente.</p>';const btn=$("#more-yesterday");if(btn)btn.onclick=()=>{expanded=!expanded;paint()}}paint()}
function render(){const s=favs();renderRecentResults();renderBriefs(s);renderPlanning(s);renderStandings(s)}
function save(){const s=[...picker.querySelectorAll("input:checked")].map(x=>x.value);try{localStorage.setItem(STORAGE_KEY,JSON.stringify(s));status.textContent=`${s.length} equipo${s.length===1?"":"s"} guardado${s.length===1?"":"s"} en este navegador.`;status.className="status"}catch{status.textContent="No se ha podido guardar la selección.";status.className="status error"}render()}
async function load(){refresh.disabled=true;refresh.textContent="Actualizando…";status.textContent="Actualizando datos reales del Mundial 2026…";status.className="status";try{const p=await(await fetch(DATA_URL)).json();events=(p.events||[]).map(normal).filter(Boolean).sort((a,b)=>a.date-b.date);const gs=new Map;events.forEach(e=>[e.home,e.away].forEach(n=>{if(!info[n])return;if(!gs.has(n)||e.group)gs.set(n,e.group||gs.get(n)||"")}));teams=[...gs.keys()].sort((a,b)=>info[a].label.localeCompare(info[b].label,"es")).map(name=>({name,group:gs.get(name)||""}));if(!events.length||teams.length<2)throw new Error("ESPN returned insufficient match or team data");console.log("[WCB] ESPN data loaded",{events:events.length,teams:teams.length});renderPicker();render();status.textContent=teams.length<48?"Datos cargados parcialmente desde ESPN.":"Datos actualizados desde ESPN."}catch(error){console.error("[WCB] ESPN load failed",error);teams=fallback.map(name=>({name,group:""}));renderPicker();render();status.textContent="No se han podido cargar los datos en directo. Tus favoritos se conservan.";status.className="status error"}finally{refresh.disabled=false;refresh.textContent="Actualizar"}}
const filter=$("#match-filter");filter.value=localStorage.getItem(FILTER_KEY)||(favs().length?"mine":"all");filter.addEventListener("change",()=>{localStorage.setItem(FILTER_KEY,filter.value);render()});refresh.addEventListener("click",load);renderPicker();load();
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));
